spring:
  profiles:
    active: window-dev

---
server:
  port: 0

port:
  number:
    min: 7050
    max: 7080
                         
logging:
  level:
    yongs:
      temp: DEBUG
      
spring:
  profiles: window-dev
  application:
    name: db-test

app:
  datasource:
    jdbc-url: jdbc:mariadb://localhost:3306/boot
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
    maximum-pool-size: 5

---
server:
  port: 8080
              
logging:
  level:
    yongs:
      temp: DEBUG
      
spring:
  profiles: docker-dev
  application:
    name: db-test

app:
  datasource:
    jdbc-url: jdbc:mariadb://maria-db:3306/boot
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
    maximum-pool-size: 5