spring:
  profiles:
    active: window-env

---
server:
  port: 0

port:
  number:
    min: 8050
    max: 8080
                         
logging:
  level:
    yongs:
      temp: DEBUG
      
spring:
  profiles: window-env
  application:
    name: db-test

app:
  datasource:
    jdbc-url: jdbc:mariadb://localhost:3306/boot
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
    maximum-pool-size: 5
                
---
server:
  port: 8080
              
logging:
  level:
    yongs:
      temp: DEBUG
      
spring:
  profiles: docker-env
  application:
    name: db-test

app:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    maximum-pool-size: 5s